### ISSUE TITLE
no leveldb @ a53934a

### ISSUE THREAD

**Issue by dbyoung720** [t-kuha/caffe-win-dependency#2]
no leveldb @ a53934a

**Comment by t-kuha** [comment]
@dbyoung720 
Thanks for your interest.
I'm yet to settle on the correct repo/version of leveldb, because google's leveldb does not support building on Windows.
I'll commit an update as soon as I find a solution.

**Comment by dbyoung720** [comment]
ok, thank

**Comment by t-kuha** [comment]
I settled on https://github.com/bureau14/leveldb (commit: 915d663).
Take a look at the repo.

**Comment by dbyoung720** [comment]
I git clone ok, thank.
