### ISSUE TITLE
build OK. is must be python2.7?

### ISSUE THREAD

**Issue by dbyoung720** [t-kuha/caffe-win-dependency#3]
build OK. is must be python2.7?

I build first, use python3.5, error. tip no python27.lib. change python2.7.14, build ok.
I guess boost is build python2.7.14

I machine installed python2.7.14 and python3.5.1.

how to open CUDA and CUDNN?

thank a lot!

**Comment by t-kuha** [comment]
@dbyoung720 
- Python 2.7 is not tested yet.
- I have successfully built against Python 3.6.2. (I think the binary in the repo is not compatible with other versions of Python.)
- To build with CUDA, you have to get CUDA SDK from NVIDIA's website.

- Tip: If you want to build against another version of Python, you have to build boost_python yourself.

**Comment by dbyoung720** [comment]
CUDA9.1, CUDNN is installed. How to modify script effect cuda?

**Comment by t-kuha** [comment]
@dbyoung720 
I have added a batch file (_build_caffe_gpu.cmd_) for that just now.
Before building, be sure to set your GPU's arch name to ***-DCUDA_ARCH_NAME=*** .

As a side note, I'm NOT sure CUDA 9 and later is compatible with the current version of Caffe for Windows. I recommend using CUDA 8.0 & cuDNN 6.0.

**Comment by t-kuha** [comment]
FYI, I have successfully built in the following environment:
  1) Python **2.7** / VS201**7** / No CUDA
  2) Python **3.6** / VS201**5** / No CUDA
  3) Python **3.6** / VS201**7** / No CUDA
  4) Python **3.6** / VS201**5** / With CUDA

**Comment by dbyoung720** [comment]
I try

**Comment by dbyoung720** [comment]
I uninstall python2.7 and 3.5, install 3.6.4.
build gpu, error.  tip no python27.lib. as before.
I guess caffe link boost, use libboost_python-, not use libboost_python3-

**Comment by dbyoung720** [comment]
I replace *.vcxproj  libboost_python-  to  libboost_python3- , build OK
my environment:
Python 3.6.4 / VS2015 / CUDA 9.1 /CUDNN7.0.5

**Comment by t-kuha** [comment]
@dbyoung720 
Thank you for the report.
As you noted, editing Visual Studio project may be the quickest solution.
